# "Smart" syntax not supported, e.g. "some folder/*.mp4" to ignore all mp4's from "some folder".
# Don't use "/" at the end of a folder path.

from_folder_path: data/from
to_folder_path: data/to
trash_path: ~/.Trash

ignore_files:
  - .DS_Store

ignore_folders:
  - .venv
  - .cache
  - .mypy_cache
  - Example folder/Example subfolder

ignore_extensions:
  - .pth
